apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: account-db
  namespace: database
spec:
  selector:
    matchLabels:
      app: account-db
  serviceName: "account-db-svc"
  replicas: 1
  template:
    metadata:
      labels:
        app: account-db
    spec:
      containers:
      - name: account-db
        image: mariadb:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: mariadb-init-config
          mountPath: /docker-entrypoint-initdb.d/
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MARIADB_ROOT_PASSWORD
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data
      - name: mariadb-init-config
        configMap:
          name: mariadb-init-config

---

apiVersion: v1
kind: Service
metadata:
  name: account-db-svc
  namespace: database
spec:
  selector:
    app: account-db
  ports:
  - port: 13305
    targetPort: 3306