apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-db-data
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rentalboard-db-data
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage