apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: nginx
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: BE-svc
spec:
  selector:
    app: BE-svc
  ports:
  - port: 3001
    targetPort: 3000
