apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: grovince/c-keeper:nodejsTEST1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: BE-svc
spec:
  selector:
    app: BE-svc
  ports:
  - port: 8081
    targetPort: 8080
