apiVersion: v1
kind: PersistentVolume
metadata:
  name: connect-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: "kafka-debezium"
  hostPath:
    path: /data/
    type: DirectoryOrCreate