apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-access-to-db-policy
  namespace: database
spec:
  podSelector:
    matchLabels:
      role: account-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: backend          
      ports:
        - protocol: TCP
          port: 3306