apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:    
      - name: nginx-conf
        configMap:
          name: nginx-conf

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80