apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  config:
    tasks.max: 1
    database.hostname: rentalboard-db-svc
    database.port: 3306
    database.user: ${secrets:debezium/debezium-secret:username}
    database.password: ${secrets:debezium/debezium-secret:password}
    database.server.id: 184054
    topic.prefix:  mariadb
    database.include.list: inventory
    schema.history.internal.kafka.bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS}
    schema.history.internal.kafka.topic: dbhistory.mariadb
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      valueFrom:
        configMapKeyRef:
          name: kafka-config
          key: KAFKA_BOOTSTRAP_SERVERS