apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
  namespace: kafka
spec:
  version: 3.1.0
  replicas: 1
  image: quay.io/debezium/connect:1.9
  #imagePullPolicy: Always
  bootstrapServers: 211.188.51.240:29092
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    group.id: debezium-mariadb-connect-cluster