apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
  labels: 
    strimzi.io/cluster: debezium-connect-cluster
  namespace: kafka
spec:
  version: 3.2.0  # Kafka 버전을 3.2.0으로 업데이트
  replicas: 1
  image: quay.io/strimzi/kafka:0.32.0-kafka-3.2.0  # Strimzi Kafka 이미지 사용
  bootstrapServers: 211.188.51.240:29092
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    group.id: debezium-mariadb-kafka-connect-cluster
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  # resources:
  #   requests:
  #     cpu: 100m 
  #     memory: 256Mi
  #   limits:
  #     cpu: 500m
  #     memory: 1Gi
  build:
    output:
      type: docker
      image: grovince/c-keeper:kafkaconnector
      pushSecret: docker-authentication
    plugins:
      - name: debezium-mariadb-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.4.0.Final/debezium-connector-mysql-2.4.0.Final-plugin.tar.gz
      - name: mariadb-jdbc-driver
        artifacts:
          - type: jar
            url: https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.27/mysql-connector-java-8.0.27.jar