apiVersion: apps/v1
kind: Deployment
metadata:
  name: DB
  namespace: database
spec:
  selector:
    matchLabels:
      app: DB
  template:
    metadata:
      labels:
        app: DB
    spec:
      containers:
      - name: DB
        image: mariadb:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: init-config
          mountPath: /docker-entrypoint-initdb.d
      initContainers:
      - name: init-mariadb
        image: busybox
        command: ['sh', '-c', 'cp /config/init.sql /docker-entrypoint-initdb.d/']
        volumeMounts:
        - name: init-config
          mountPath: /config
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data
      - name: init-config
        configMap:
          name: mariadb-init-config

---

apiVersion: v1
kind: Service
metadata:
  name: DB-svc
  namespace: database
spec:
  selector:
    app: DB
  ports:
  - port: 13305
    targetPort: 3306
