apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: database
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mariadb:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: init-config
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: MARIADB_ROOT_PASSWORD
      initContainers:
      - name: init-mariadb
        image: busybox
        command: ['sh', '-c', 'cp /config/init.sql /docker-entrypoint-initdb.d']
        volumeMounts:
        - name: init-config
          mountPath: /config
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data
      - name: init-config
        configMap:
          name: mariadb-init-config

---

apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: database
spec:
  selector:
    app: db
  ports:
  - port: 13305
    targetPort: 3306