apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-chat
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-chat
  template:
    metadata:
      labels:
        app: backend-chat
    spec:
      containers:
      - name: backend-chat
        image: grovince/c-keeper:chat-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 9992

---

apiVersion: v1
kind: Service
metadata:
  name: backend-chat-svc
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: backend-chat
  ports:
    - protocol: TCP
      port: 9992
      targetPort: 9992